### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by damar1st** [NyaMisty/ipatool-py#21]
Hey,
i am getting this new error if i try to download the com.ea.simpsonssocial.inc2 IPA with the purchase option.

`<Class StoreBuyproductResp. pings: [], jingleDocType: None, jingleAction: None, status: None, dsPersonId: None, creditDisplay: None, creditBalance: None, freeSongBalance: None, creditDisplayInternal: None, authorized: None, download_
queue_item_count: None, songList: None, download_queue_info: None, metrics: <Class _metri...ype: 'dialog'>, duAnonymousPings: None, subscriptionStatus: None, cancel_purchase_batch: None, failureType: '2059', customerMessage: 'This it
em is... unavailable.', m_allowed: False, dialog: <Class _dialo...oxValue: True>>
Traceback (most recent call last):
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 326, in <module>
    main()
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 324, in main
    tool.tool_main()
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 131, in tool_main
    args.func(args)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 252, in handleDownload
    Store.purchase(self.appId)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\reqs\store.py", line 175, in purchase
    return self.buyProduct_purchase(appId)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\reqs\store.py", line 168, in buyProduct_purchase
    resp.status + '-' + resp.jingleDocType)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
'
`

If i try to download it without the purchase option ill get this error:

`<Logger main (INFO)>
<Class StoreDownloadResp. pings: [], cancel_purchase_batch: True, customerMessage: 'License not found.', failureType: '9610', jingleDocType: None, jingleAction: None, status: None, dsPersonId: None, creditDisplay: None, creditBalance
: None, freeSongBalance: None, authorized: None, download_queue_item_count: None, songList: None, metrics: None, subscriptionStatus: None>
Traceback (most recent call last):
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 326, in <module>
    main()
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 324, in main
    tool.tool_main()
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 131, in tool_main
    args.func(args)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\main.py", line 261, in handleDownload
    downResp = Store.download(self.appId, self.appVerId)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\reqs\store.py", line 181, in download
    return self.volumeStoreDownloadProduct(appId, appVer)
  File "C:\Users\hacker\PycharmProjects\pythonProject1\ipa\reqs\store.py", line 87, in volumeStoreDownloadProduct
    resp.failureType + '-' + resp.metrics.dialogId)
AttributeError: 'NoneType' object has no attribute 'dialogId'
`
Any idea ?

**Comment by ImVantexHD** [comment]
im also getting the same error, the only argument that works is "lookup", which is not very helpful :(

**Comment by damar1st** [comment]
It seems the request for the store download is not correct at all.
I'll check my mitmproxy, maybe ill find a fix for it.

**Comment by ImVantexHD** [comment]
so.. have you managed to fix it? is the api store request wrong after all?
i don't have a mac or iphone to test this otherwise I would have used the original "ipatool", not sure if there are any other tools that can also work for windows/linux but that are still maintained

**Comment by NyaMisty** [comment]
The error handling was fixed, sorry for the late :(
