### ISSUE TITLE
Unable to purchase app

### ISSUE THREAD

**Issue by skintclover** [NyaMisty/ipatool-py#29]
Error when trying to download purchase ipa

Traceback (most recent call last):
  File "/home/npham/ipatool-py/main.py", line 325, in <module>
    main()
  File "/home/npham/ipatool-py/main.py", line 323, in main
    tool.tool_main()
  File "/home/npham/ipatool-py/main.py", line 131, in tool_main
    args.func(args)
  File "/home/npham/ipatool-py/main.py", line 252, in handleDownload
    Store.purchase(self.appId)
  File "/home/npham/ipatool-py/reqs/store.py", line 169, in purchase
    return self.buyProduct_purchase(appId)
  File "/home/npham/ipatool-py/reqs/store.py", line 162, in buyProduct_purchase
    resp.status + '-' + resp.jingleDocType)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Pls help me!

**Comment by MikePendo** [comment]
I have the same issue. Although I did manage to use it previously, 
How to display the actually error?

**Comment by NyaMisty** [comment]
I've updated to show underlying error, please retry and give me new error message :)
I'll close this issue. If you got time to try again, let me know :)
