### ISSUE TITLE
Unable to download old version of apps

### ISSUE THREAD

**Issue by AhmadAradii** [NyaMisty/ipatool-py#31]
After struggling to make the server work i stumble upon this issue when i tried to download an old version of an app to test out the tool:

```
Traceback (most recent call last):
  File "D:\Downloads\IPA Downloaders\ipatool-py\main.py", line 325, in <module>
    main()
  File "D:\Downloads\IPA Downloaders\ipatool-py\main.py", line 323, in main
    tool.tool_main()
  File "D:\Downloads\IPA Downloaders\ipatool-py\main.py", line 131, in tool_main
    args.func(args)
  File "D:\Downloads\IPA Downloaders\ipatool-py\main.py", line 261, in handleDownload
    downResp = Store.download(self.appId, self.appVerId)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\IPA Downloaders\ipatool-py\reqs\store.py", line 173, in download
    return self.buyProduct(appId, appVer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\IPA Downloaders\ipatool-py\reqs\store.py", line 92, in buyProduct
    itunes_internal = self.iTunes_provider(url)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\IPA Downloaders\ipatool-py\main.py", line 180, in handle_iTunes_provider
    r = requests.get(servUrl, params={
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http:127.0.0.1:9000': No host supplied
```

**Comment by easypeasy12310** [comment]
Hi, how did you solve this? Thanks.
