### ISSUE TITLE
Itunes server just stopped working after a few download alls

### ISSUE THREAD

**Issue by Zweronz** [NyaMisty/ipatool-py#57]
so, I set up the itunes server thing on my windows 10 computer, and it worked fine. I went to go make an automatic scraping tool since downloadVersionAll is kind of buggy, I run a test command for historyver, it doesn't work. ever since that point not a single command has worked on the itunes server.

I've logged out, logged in, reinstalled itunes, repatched it, restarted my computer, authorized my computer, restarted the server, again and again and I keep getting this error:

Traceback (most recent call last):
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\reqs\itunes.py", line 41, in getAppVerId
    appParam = re.findall(r'"buyParams":"(.*?)"', appInfo)[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\main.py", line 566, in <module>
    main()
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\main.py", line 563, in main
    tool.tool_main()
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\main.py", line 187, in tool_main
    args.func(args)
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\main.py", line 438, in handleDownload
    self.downloadOne(args)
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\main.py", line 460, in downloadOne
    downResp = Store.download(self.appId, self.appVerId, isRedownload=not args.purchase)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\reqs\store.py", line 252, in download
    return self.buyProduct(appId, appVer, pricingParameters='STDRDL' if isRedownload else 'STDQ')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\reqs\store.py", line 171, in buyProduct
    appVer = iTunes.getAppVerId(appId, hdrs['X-Apple-Store-Front'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ender\Downloads\ipatool-py-master\ipatool-py-master\reqs\itunes.py", line 43, in getAppVerId
    appParam = re.findall(r'buy-params="(.*?)"', appInfo)[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

the first and only time it worked was when I first followed the steps, I tried restarting from the beginning, just uninstalling everything I did, and it didn't fix it.

python main.py download --itunes-server "http://192.168.254.74:9000" --appId 480523239

downloading manually with email and password still works fine, but this doesn't

**Comment by easypeasy12310** [comment]
Hi, how did you get your itunes server? I ran: "actions-iTunes-header/workflow_helper/iTunesDownload/get_header.py" but it does nothing. Do I need to run it in something else? Please let me know. Thanks.
