### ISSUE TITLE
2FA Crash. 

### ISSUE THREAD

**Issue by losywee** [NyaMisty/ipatool-py#9]
Password+2FA not work.

Traceback (most recent call last):
  File "main.py", line 247, in handleDownload
    Store = self._get_StoreClient(args)
  File "main.py", line 199, in _get_StoreClient
    Store.authenticate(appleid, applepass)
  File "/private/tmp/ipatool-py-master/reqs/store.py", line 44, in authenticate
    raise StoreException("authenticate", resp.customerMessage, resp.failureType)
reqs.store.StoreException: Store authenticate error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 325, in <module>
    main()
  File "main.py", line 323, in main
    tool.tool_main()
  File "main.py", line 131, in tool_main
    args.func(args)
  File "main.py", line 318, in handleDownload
    self._handleStoreException(e)
  File "main.py", line 206, in _handleStoreException
    logger.fatal("    Raw Response: %s" % (e.resp.as_dict()))
AttributeError: 'str' object has no attribute 'as_dict'

**Comment by ImVantexHD** [comment]
have you solved it?
i'm getting this:

```
Traceback (most recent call last):
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 325, in <module>
    main()
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 323, in main
    tool.tool_main()
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 131, in tool_main
    args.func(args)
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 261, in handleDownload
    downResp = Store.download(self.appId, self.appVerId)
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\reqs\store.py", line 175, in download
    return self.volumeStoreDownloadProduct(appId, appVer)
  File "C:\Users\Marian\Desktop\Programs\ipatool-py\reqs\store.py", line 85, in volumeStoreDownloadProduct
    raise StoreException("volumeStoreDownloadProduct", resp, resp.customerMessage, resp.failureType + '-' + resp.metrics.dialogId)
AttributeError: 'NoneType' object has no attribute 'dialogId'
```

**Comment by ImVantexHD** [comment]
> have you solved it? i'm getting this:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 325, in <module>
>     main()
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 323, in main
>     tool.tool_main()
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 131, in tool_main
>     args.func(args)
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\main.py", line 261, in handleDownload
>     downResp = Store.download(self.appId, self.appVerId)
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\reqs\store.py", line 175, in download
>     return self.volumeStoreDownloadProduct(appId, appVer)
>   File "C:\Users\Marian\Desktop\Programs\ipatool-py\reqs\store.py", line 85, in volumeStoreDownloadProduct
>     raise StoreException("volumeStoreDownloadProduct", resp, resp.customerMessage, resp.failureType + '-' + resp.metrics.dialogId)
> AttributeError: 'NoneType' object has no attribute 'dialogId'
> ```

What python version is recommended to use for this tool? i'm still getting the above error using python 3.9.6
the only argument that works is "lookup", the other two "historyver" and "download" will fail with the above error.

**Comment by darkworks** [comment]
same issue same error 2fa not working

**Comment by MikePendo** [comment]
The adove of @darkworks worked for me
